# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed_rainpool <- function(seed) {
    invisible(.Call(`_rainpool_set_seed_rainpool`, seed))
}

rbinom_rainpool <- function(n, size, prob) {
    .Call(`_rainpool_rbinom_rainpool`, n, size, prob)
}

